/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/components/404.vue')['default']
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    ArchivePage: typeof import('./src/components/ArchivePage.vue')['default']
    ContactPage: typeof import('./src/components/ContactPage.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    MyFooter: typeof import('./src/components/MyFooter.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostPage: typeof import('./src/components/PostPage.vue')['default']
    SearchDPage: typeof import('./src/components/SearchDPage.vue')['default']
    SearchPage: typeof import('./src/components/SearchPage.vue')['default']
    TagPage: typeof import('./src/components/TagPage.vue')['default']
    TagsPage: typeof import('./src/components/TagsPage.vue')['default']
    YearPage: typeof import('./src/components/YearPage.vue')['default']
  }
}
